name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            artifact_name: Pyp
            architecture: osx-amd64
            asset_name: pyp-macos-amd64
          - os: macos-latest
            artifact_name: Pyp
            architecture: osx-arm64
            asset_name: pyp-macos-arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: dotnet restore
      - run: dotnet publish -r ${{ matrix.architecture }} -c Release /p:AssemblyVersion=${{ github.ref }} /p:Version=${{ github.ref }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Pyp/bin/Release/net8.0/${{ matrix.architecture }}/publish/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
